### ISSUE TITLE
Total test count and pass count is wrong

### ISSUE THREAD

**Issue by adam-lynch** [shuhei/colortape#2]
![image](https://cloud.githubusercontent.com/assets/1427241/5417675/90d38872-8233-11e4-9958-1a00e1320c0a.png)

No idea why.

**Comment by kylegmaxwell** [comment]
@shuhei I have the same problem. Tape works, but colortape does not. Here is a minimal example. The first test passes but is reported incorrectly by colortape. The second test fails and is incorrectly reported as a success by colortape.

Create a folder with two files.
1. package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "tape test.js",
    "color": "colortape test.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "colortape": "^0.1.1",
    "tape": "^4.6.3"
  }
}

2. test.js
'use strict';

var test = require('tape');

test('Simple test', function (t) {
    t.ok(true, 'This is true');
    t.end();
});

test('Advanced test', function (t) {
    Promise.resolve(true).then(function () {
        apple.orange;
        t.ok(true, 'This is true');
        t.end();
    }).catch(function (err) {
        t.ok(false, err);
        t.end();
    });
});

Then run 'npm test' to see tape's output and 'npm run color' to see the colortape output.

**Comment by kylegmaxwell** [comment]
Sample output:
~> npm test

> test@1.0.0 test ~
> tape test.js

TAP version 13
# Simple test
ok 1 This is true
# Advanced test
not ok 2 ReferenceError: apple is not defined
  ---
    operator: ok
    expected: true
    actual:   false
    at: process._tickCallback (internal/process/next_tick.js:103:7)
  ...

1..2
# tests 2
# pass  1
# fail  1

npm ERR! Test failed.  See above for more details.
~> npm run color

> test@1.0.0 color ~
> colortape test.js

TAP version 13
# Simple test
ok 1 This is true
# Advanced test
not ok 2 ReferenceError: apple is not defined
  ---
    operator: ok
    expected: true
    actual:   false
    at: process._tickCallback (internal/process/next_tick.js:103:7)
  ...
TAP version 13

1..0
# tests 0
# pass  0

# ok

**Comment by kylegmaxwell** [comment]
yeah, sorry, i noticed it came in as markdown, fixed now. thanks for the prompt notice

**Comment by shuhei** [comment]
@kylegmaxwell Thanks! I will look at the tests when I arrive home.

**Comment by shuhei** [comment]
I confirmed that it actually happens with obally installed colortape bin. But somehow it doesn't happen with the repo's bin. I will investigate why.

**Comment by shuhei** [comment]
Should be fixed in 0.1.2.

**Comment by kylegmaxwell** [comment]
I don't think I have it installed globally, but it works now, so thanks!

**Comment by shuhei** [comment]
Ah, yes, it could also happen when you have a different version of `tape`  from `colortape`'s.
